name: Tests

on:
    pull_request:
      branches: [ master, main ]
    push:
      branches: [ master, main ]

jobs:
    run-tests:
        uses: ./.github/workflows/tests.yml
        secrets: inherit
    